version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.16
  maven: circleci/maven@0.0.12

workflows:
  shellcheck:
    jobs:
      - shellcheck/check:
        pre-steps:
          - run:
            name: "Generate Boms"
            command: |
              scripts/generateBoms.sh          
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

